name: abherbs_flutter
description: Flutter version of abherbs

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 6.1.1+647

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: 0.5.8
  firebase_messaging: 6.0.16
  firebase_analytics: 5.0.16
  firebase_auth: 0.16.1
  firebase_storage: 3.1.6
  firebase_database: 3.1.6
  firebase_remote_config: 0.3.1+1
  google_sign_in: 4.5.1
  apple_sign_in: 0.1.0
  device_info: 0.4.2+4
  flutter_crashlytics: 1.0.0
  in_app_purchase: 0.3.4+3
  cached_network_image: 2.2.0+1
  url_launcher: 5.5.0
  http: 0.12.2
  fluttertoast: 7.0.2
  diacritic: 0.1.1
  path_provider: 1.6.11
  percent_indicator: 2.1.5
  package_info: 0.4.1
  google_maps_flutter: 0.5.28+1
  image_picker: 0.6.7+4
  exif: 1.0.3
  datetime_picker_formfield: 1.0.0
  connectivity: 0.4.9
  photo_view: 0.9.2
  admob_flutter: 1.0.0-beta.5
  screen: 0.0.5
  flutter_country_picker: 0.1.6
  charts_flutter: 0.9.0

  firebase_ml_vision:
    path: ../flutterfire/packages/firebase_ml_vision

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  intl_translation: ^0.17.9


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - res/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
flutter_intl:
  enabled: true
